import { Card } from "./types";

// Generate mock data for initial board state
export const mockCards: Card[] = [
  {
    id: "1",
    title: "Login with expired token",
    status: "blocked",
    priority: "high",
    tags: ["auth", "regression", "api", "security"],
    notes: "User cannot login when token expires. Need to verify token refresh logic.",
    links: [
      { id: "l1", label: "Jira", url: "https://jira.example.com/TEST-123" },
      { id: "l2", label: "PR", url: "https://github.com/example/pr/456" },
    ],
    blockedReason: "Waiting for fix in build 1.4.2",
    evidenceCaptured: true,
    evidenceNotes: "Screenshots and logs attached to Jira",
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: "2",
    title: "Verify password reset flow",
    status: "in-progress",
    priority: "high",
    tags: ["auth", "email"],
    notes: "Testing complete password reset flow including email delivery and link expiration.",
    links: [{ id: "l3", label: "Test case", url: "https://docs.example.com/test-cases/567" }],
    evidenceCaptured: false,
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: "3",
    title: "Dashboard loading performance",
    status: "not-started",
    priority: "medium",
    tags: ["performance", "ui"],
    notes: "Measure and document dashboard loading times under various conditions.",
    links: [],
    evidenceCaptured: false,
    createdAt: Date.now() - 86400000,
  },
  {
    id: "4",
    title: "API rate limiting tests",
    status: "done",
    priority: "high",
    tags: ["api", "performance"],
    notes: "Verified rate limiting works correctly. 429 status returned after limit exceeded.",
    links: [
      { id: "l4", label: "Jira", url: "https://jira.example.com/TEST-124" },
      { id: "l5", label: "Environment", url: "https://staging.example.com" },
    ],
    evidenceCaptured: true,
    createdAt: Date.now() - 86400000 * 5,
  },
  {
    id: "5",
    title: "Mobile responsive checkout",
    status: "in-progress",
    priority: "medium",
    tags: ["mobile", "ui", "checkout"],
    notes: "Testing checkout flow on various mobile devices and screen sizes.",
    links: [],
    evidenceCaptured: false,
    createdAt: Date.now() - 86400000,
  },
  {
    id: "6",
    title: "Payment gateway integration",
    status: "blocked",
    priority: "high",
    tags: ["payment", "api", "integration"],
    notes: "Cannot complete testing due to sandbox environment issues.",
    links: [],
    blockedReason: "Sandbox environment is down, ticket raised with vendor",
    evidenceCaptured: false,
    createdAt: Date.now() - 86400000 * 4,
  },
  {
    id: "7",
    title: "Search functionality accuracy",
    status: "not-started",
    priority: "low",
    tags: ["search", "ui"],
    notes: "",
    links: [],
    evidenceCaptured: false,
    createdAt: Date.now(),
  },
  {
    id: "8",
    title: "User profile update validation",
    status: "done",
    priority: "medium",
    tags: ["validation", "api", "ui"],
    notes: "All validation rules working correctly. Edge cases handled.",
    links: [{ id: "l6", label: "Jira", url: "https://jira.example.com/TEST-125" }],
    evidenceCaptured: true,
    evidenceNotes: "Postman collection with all test cases",
    createdAt: Date.now() - 86400000 * 6,
  },
  {
    id: "9",
    title: "Export data to CSV",
    status: "not-started",
    priority: "low",
    tags: ["export", "feature"],
    notes: "",
    links: [],
    evidenceCaptured: false,
    createdAt: Date.now(),
  },
  {
    id: "10",
    title: "Email notification preferences",
    status: "in-progress",
    priority: "low",
    tags: ["email", "settings"],
    notes: "Testing email opt-in/opt-out functionality.",
    links: [],
    evidenceCaptured: false,
    createdAt: Date.now() - 86400000,
  },
  {
    id: "11",
    title: "Database migration rollback",
    status: "done",
    priority: "high",
    tags: ["database", "deployment"],
    notes: "Rollback procedure tested successfully. No data loss.",
    links: [
      { id: "l7", label: "Jira", url: "https://jira.example.com/TEST-126" },
      { id: "l8", label: "Commit", url: "https://github.com/example/commit/abc123" },
    ],
    evidenceCaptured: true,
    createdAt: Date.now() - 86400000 * 7,
  },
  {
    id: "12",
    title: "Multi-language support",
    status: "not-started",
    priority: "medium",
    tags: ["i18n", "ui"],
    notes: "",
    links: [],
    evidenceCaptured: false,
    createdAt: Date.now(),
  },
];
